ATiltedTree/ytextract

.github/dependabot.yml
.github/mergify.yml
.github/workflows/audit.yml
.github/workflows/main.yml
.github/workflows/test.yml
Cargo.toml
src/channel.rs
src/client.rs
src/error.rs
src/id.rs
src/lib.rs
src/thumbnail.rs
src/utils.rs
src/video.rs

This does not include stream extraction. That will come later.
Fixes: #1

feat(video): Initial Video extraction

---

Cargo.toml
src/channel.rs
src/client.rs
src/error.rs
src/id.rs
src/lib.rs
src/player.rs
src/playlist.rs
src/playlist/test.rs
src/playlist/video.rs
src/stream.rs
src/stream/audio.rs
src/stream/common.rs
src/stream/video.rs
src/thumbnail.rs
src/video.rs
src/youtube.rs
src/youtube/browse/continuation.rs
src/youtube/browse/mod.rs
src/youtube/browse/playlist.rs
src/youtube/innertube.rs
src/youtube/player_response.rs
src/youtube/video_info.rs
src/youtube/ytcfg.rs

This is still missing author and views but the general part works.
Fixes #2

feat: Playlists

---

Cargo.toml
src/channel.rs
src/client.rs
src/error.rs
src/id.rs
src/lib.rs
src/player.rs
src/playlist.rs
src/playlist/video.rs
src/stream.rs
src/stream/common.rs
src/video.rs
src/youtube.rs
src/youtube/browse/channel/about.rs
src/youtube/browse/channel/mod.rs
src/youtube/browse/mod.rs
src/youtube/browse/playlist.rs
src/youtube/innertube.rs
src/youtube/player_response.rs
src/youtube/tv_config.rs
src/youtube/ytcfg.rs
tests/channel.rs
tests/playlist.rs
tests/video.rs

This is currently missing related channels and created playlists.
Closes: #4 
Signed-off-by: Tilmann Meyer <me@atiltedtree.dev>

feat: Channel

---

src/error.rs
src/youtube/browse/mod.rs
src/youtube/innertube.rs
src/youtube/player_response.rs
tests/channel.rs
tests/playlist.rs
tests/stream.rs
tests/video.rs

Fixes error handling for videos, streams, playlists and channels. Also adds tests for error handling.

fix: Better error handling

---

src/channel.rs
src/error.rs
src/id.rs
src/lib.rs
src/playlist.rs
src/playlist/video.rs
src/stream.rs
src/stream/audio.rs
src/stream/common.rs
src/stream/video.rs
src/thumbnail.rs
src/video.rs
src/youtube/browse/channel/about.rs
src/youtube/browse/channel/mod.rs
src/youtube/browse/playlist.rs
src/youtube/player_response.rs

Signed-off-by: Tilmann Meyer <me@atiltedtree.dev>

feat: Implement Clone, PartialEq and Eq for most types

---

.github/workflows/main.yml

Signed-off-by: Tilmann Meyer <me@atiltedtree.dev>

ci: Make sure that documentation builds successfully

---

src/playlist.rs
src/youtube/browse/playlist.rs
src/youtube/innertube.rs

feat(playlist): Remove lifetime constraint from `videos()`

---

examples/channel.rs
src/channel.rs

feat(channel): Just return videos for `uploads`

---

tests/playlist.rs

Added a movie to the test playlist to make sure it parses.
Also changed the view count assert to remove the attributes.
bors r+

test(playlist): Test for Movie

---

src/channel.rs
src/playlist.rs
src/playlist/video.rs
src/youtube.rs
src/youtube/browse/channel/mod.rs
src/youtube/browse/mod.rs
src/youtube/browse/playlist.rs

chore: Remove duplicate definitions

---

src/video.rs
src/youtube.rs
src/youtube/innertube.rs
src/youtube/next.rs
tests/video.rs

This now correctly parses the JSON returned from `next` and uses it.
bors r+

feat(video): Add hashtags and channel subscriber count

---

examples/related.rs
src/video.rs
src/video/related.rs
src/youtube.rs
tests/video.rs

feat(video): Add extraction of related items

---

Cargo.toml
src/video/related.rs
src/youtube/innertube.rs
src/youtube/next.rs
src/youtube/player_response.rs
tests/stream.rs
tests/video.rs

A roundup of new fixes

---

src/youtube.rs
tests/video.rs

fix(video): Fix parsing of dates from premiered videos

---

Cargo.toml
tests/channel.rs
tests/playlist.rs
tests/stream.rs
tests/video.rs

When this gets stabilized in `std` switch to it
bors r+

test: Use assert_matches

---

src/youtube/innertube.rs

chore(innertube): Enable dumping with `YTEXTRACT_DUMP` env variable

---

src/stream.rs
src/youtube/innertube.rs
src/youtube/player_response.rs

chore(player_response): Cleanup

---

src/youtube/next.rs
src/youtube/player_response.rs

Add new button type and fix error reasons

---

src/playlist.rs
src/video.rs
src/youtube.rs
src/youtube/next.rs
tests/playlist.rs

Remove broken tests and add `CompactPromotedVideoRenderer`

---

src/youtube/innertube.rs

Request will timeout after 5 seconds and will retry 5 times. Sometimes
youtube does not respond so timeout and try our luck again!
Fixes #74

fix(client): Add retrys and timeouts

---

src/error.rs
src/youtube/next.rs
src/youtube/player_response.rs
tests/video.rs

Added some strings, and tests, and some other minor fixes

Fix errors

---

Cargo.toml

feat: Use rustls

---

src/stream.rs
src/youtube/innertube.rs
tests/stream.rs

fix(stream): Allow downloading of non embed-restricted age-restricted videos

---

tests/channel.rs

tests(channel): Remove dead test
